import os
import google.generativeai as genai
from dotenv import load_dotenv

load_dotenv()

def detect_ai_content(text):
    """
    Analyzes text using Gemini API to determine the probability of it being AI-generated.
    Returns a score from 0-100.
    """
    if not text or len(text.strip()) < 50:
        return 0  # Not enough text to analyze reliably

    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("[AI ERROR] No GEMINI_API_KEY found in environment.")
        return 0

    try:
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel("gemini-1.5-flash")
        
        prompt = f"""
        Analyze the following text and determine the probability (0 to 100) that it was generated by an AI language model (like ChatGPT, Claude, or Gemini).
        
        Provide only a single integer representing the probability percentage. Do not include any explanation or other text.
        
        Text to analyze:
        ---
        {text[:5000]}  # Limit text to 5000 chars for analysis
        ---
        """
        
        response = model.generate_content(prompt)
        # Extract numbers from response
        import re
        match = re.search(r'\d+', response.text)
        if match:
            score = int(match.group())
            return min(max(score, 0), 100) # Ensure it's between 0-100
        else:
            print(f"[AI ERROR] Unexpected response format from Gemini: {response.text}")
            return 0
            
    except Exception as e:
        print(f"[AI ERROR] Gemini analysis failed: {e}")
        return 0
